name: Deploy to Railway

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Link project to Railway (Dev)
        run: |
          railway link --team "${{ secrets.RAILWAY_DEV_TEAM_ID }}" --project "${{ secrets.RAILWAY_DEV_PROJECT_ID }}"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway (Dev)
        run: |
          railway up --service "${{ secrets.RAILWAY_DEV_SERVICE_ID }}"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy_dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Wait for approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Link project to Railway (Prod)
        run: |
          railway link --team "${{ secrets.RAILWAY_PROD_TEAM_ID }}" --project "${{ secrets.RAILWAY_PROD_PROJECT_ID }}"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway (Prod)
        run: |
          railway up --service "${{ secrets.RAILWAY_PROD_SERVICE_ID }}"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}