name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Link project to Railway
        run: |
          railway link --project ${{ secrets.RAILWAY_PROD_PROJECT_ID }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway
        run: |
          railway up --service ${{ secrets.RAILWAY_PROD_SERVICE_ID }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}